name = "NNDynamics"
uuid = "53ea632b-59b7-4298-9872-46979de5c8eb"
authors = ["Sven Duve <svenduve@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
